/*
 * File: app/view/VitalsForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoApp.view.VitalsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.vitalsform',

    requires: [
        'Ext.field.Select',
        'Ext.field.TextArea',
        'Ext.Button'
    ],

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'textfield',
                id: 'txtVitalsday',
                label: 'Choose date',
                //labelWidth: '35%',
                component:{type: 'date'}
            },
            {
                xtype: 'textfield',
                label: 'Oxygen'
            },
            {
                xtype: 'textfield',
                label: 'HeartRate'
            },
            {
                xtype: 'textfield',
                label: 'BP'
            },
            {
                xtype: 'textfield',
                label: 'Glucose'
            },
            {
                xtype: 'textfield',
                label: 'Weight'
            },
            {
                xtype: 'selectfield',
                label: 'Do you have SOB?',
                labelWidth: '70%'
            },
            {
                xtype: 'selectfield',
                label: 'Have you had a cough?',
                labelWidth: '70%'
            },
            {
                xtype: 'selectfield',
                label: 'Do you have swelling?',
                labelWidth: '70%'
            },
            {
                xtype: 'selectfield',
                label: 'Are you using oxygen?',
                labelWidth: '70%'
            },
            {
                xtype: 'selectfield',
                label: 'Have you taken medications regularly?',
                labelWidth: '70%',
                labelWrap: true
            },
            {
                xtype: 'textareafield',
                label: 'Additional Comments',
                labelAlign: 'top'
            },
            {
                xtype: 'button',
                height: 36,
                itemId: 'pressSUBMIT',
                text: 'SUBMIT'
            }
        ]
    }

});