/*
 * File: app/view/Firstcontainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoApp.view.Firstcontainer', {
    extend: 'Ext.Container',
    alias: 'widget.firstcontainer',

    requires: [
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Img'
    ],

    config: {
        padding: 40,
        items: [
            {
                xtype: 'button',
                height: 54,
                text: 'New User? SIGN UP'
            },
            {
                xtype: 'spacer',
                height: 26
            },
            {
                xtype: 'image',
                height: 201,
                src: 'heartbeat.jpg'
            },
            {
                xtype: 'spacer',
                height: 30
            },
            {
                xtype: 'button',
                height: 54,
                text: 'LOGIN'
            }
        ]
    }

});