/*
 * File: app/view/LoginContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoApp.view.LoginContainer', {
    extend: 'Ext.Container',
    alias: 'widget.logincontainer',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'formpanel',
                id: 'dataForm',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Login',
                        items: [
                            {
                                xtype: 'emailfield',
                                label: 'EmailId',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'passwordfield',
                                label: 'Passwd'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        iconAlign: 'center',
                        text: 'LOGIN'
                    }
                ]
            }
        ]
    }

});