/*
 * File: app/view/MainNav.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoApp.view.MainNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainnav',

    requires: [
        'DemoApp.view.Firstcontainer',
        'DemoApp.view.LoginContainer',
        'DemoApp.view.SignContainer',
        'DemoApp.view.UserPanel',
        'DemoApp.view.VitalsForm',
        'Ext.form.Panel'
    ],

    config: {
        items: [
            {
                xtype: 'firstcontainer'
            },
            {
                xtype: 'logincontainer',
                title: 'formcontainer'
            },
            {
                xtype: 'signcontainer',
                title: 'infocontainer'
            },
            {
                xtype: 'userpanel',
                title: 'vitalSignsPanel'
            },
            {
                xtype: 'vitalsform'
            }
        ]
    }

});