/*
 * File: app/view/SignContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoApp.view.SignContainer', {
    extend: 'Ext.Container',
    alias: 'widget.signcontainer',

    requires: [
        'Ext.TitleBar',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Email',
        'Ext.field.Password'
    ],

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'SIGN UP'
            },
            {
                xtype: 'textfield',
                label: 'Name'
            },
            {
                xtype: 'selectfield',
                label: 'Gender'
            },
            {
                xtype: 'datepickerfield',
                label: 'Birthdate',
                placeHolder: 'mm/dd/yyyy'
            },
            {
                xtype: 'textfield',
                label: 'Weight'
            },
            {
                xtype: 'textfield',
                label: 'HospitalID'
            },
            {
                xtype: 'emailfield',
                label: 'emailID',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                label: 'Passwd'
            },
            {
                xtype: 'passwordfield',
                height: 73,
                label: 'Retype Passwd',
                labelWrap: true
            },
            {
                xtype: 'button',
                text: 'SIGN UP'
            }
        ]
    }

});